spring.application.name=postService
server.port = 9010
spring.datasource.url=jdbc:postgresql://localhost:5432/ln-userDB
spring.datasource.username=gourav
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update