spring.application.name=userService
server.port = 9020
spring.datasource.url=jdbc:postgresql://localhost:5432/ln-postDB
spring.datasource.username=gourav
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update