spring.application.name=userService
server.port = 9020
server.servlet.context-path=/users
spring.datasource.url=jdbc:postgresql://localhost:5432/ln-userDB
spring.datasource.username=gourav
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update


jwt.secretKey = asdfuasjf9a8s7fd89ihq34kljruyf98ayshcskdhfioafsuyfdcjha890sduf

eureka.client.service-url.defaultZone=http://localhost:8761/eureka